import { Trade, Account, Playbook, PsychologyEntry } from '@/types'
import { subDays, subHours, format } from 'date-fns'

const now = new Date()

export const MOCK_ACCOUNT: Account = {
  id: 'acc-1',
  user_id: 'user-1',
  name: 'Interactive Brokers',
  broker: 'Interactive Brokers',
  asset_type: 'stocks',
  initial_balance: 50000,
  currency: 'USD',
  is_default: true,
  created_at: subDays(now, 90).toISOString(),
}

export const MOCK_PLAYBOOKS: Playbook[] = [
  {
    id: 'pb-1',
    user_id: 'user-1',
    name: 'VWAP Breakout',
    description: 'Trade breakouts above VWAP with volume confirmation',
    asset_type: 'stocks',
    timeframe: '5m',
    market_conditions: 'Trending, high volume',
    entry_rules: ['Price breaks above VWAP', 'Volume > 2x average', 'Momentum > 0'],
    exit_rules: ['Take profit at R2', 'Stop loss at VWAP'],
    risk_rules: ['Max 2% account risk per trade', 'No trades in first 15 min'],
    notes: 'Best on high volume days',
    color: '#6366f1',
    is_active: true,
    created_at: subDays(now, 80).toISOString(),
  },
  {
    id: 'pb-2',
    user_id: 'user-1',
    name: 'Opening Range Breakout',
    description: 'Trade breakouts from the opening 15-minute range',
    asset_type: 'stocks',
    timeframe: '15m',
    market_conditions: 'Volatile open, gap days',
    entry_rules: ['Define ORB at 9:45 AM', 'Break with volume', 'Above premarket high'],
    exit_rules: ['R:R at least 2:1', 'EOD close if still open'],
    risk_rules: ['1.5% max risk', 'Size down on Mondays'],
    notes: 'Avoid on low float stocks',
    color: '#22c55e',
    is_active: true,
    created_at: subDays(now, 70).toISOString(),
  },
  {
    id: 'pb-3',
    user_id: 'user-1',
    name: 'Pullback to EMA',
    description: 'Buy pullbacks to 9/21 EMA in an uptrend',
    asset_type: 'stocks',
    timeframe: '1h',
    market_conditions: 'Uptrending market',
    entry_rules: ['Price pulls back to 9 EMA', 'Higher high structure intact', 'RSI > 40'],
    exit_rules: ['Previous high as target', 'Break of EMA as stop'],
    risk_rules: ['Max 1% risk', 'No more than 3 open trades'],
    notes: 'Works best on SPY and QQQ',
    color: '#f59e0b',
    is_active: true,
    created_at: subDays(now, 60).toISOString(),
  },
]

function generateTrade(
  daysAgo: number,
  symbol: string,
  side: 'long' | 'short',
  entry: number,
  qty: number,
  pnlTarget: number,
  playbookId: string,
  setup: string,
  emotion: 'calm' | 'anxious' | 'confident' | 'fearful' | 'greedy' = 'calm'
): Trade {
  const entryDate = subDays(now, daysAgo)
  const exitDate = subHours(entryDate, -2)
  const commission = qty * 0.005
  const pnlPerShare = pnlTarget / qty
  const exitPrice = side === 'long' ? entry + pnlPerShare : entry - pnlPerShare
  const grossPnl = pnlTarget
  const netPnl = grossPnl - commission
  const stopLoss = side === 'long' ? entry * 0.98 : entry * 1.02
  const rRisk = Math.abs(entry - stopLoss) * qty

  return {
    id: `trade-${daysAgo}-${symbol}`,
    user_id: 'user-1',
    account_id: 'acc-1',
    symbol,
    asset_type: 'stocks',
    side,
    quantity: qty,
    entry_price: entry,
    exit_price: parseFloat(exitPrice.toFixed(2)),
    entry_date: entryDate.toISOString(),
    exit_date: exitDate.toISOString(),
    stop_loss: stopLoss,
    take_profit: side === 'long' ? entry * 1.04 : entry * 0.96,
    commission,
    gross_pnl: grossPnl,
    net_pnl: netPnl,
    r_multiple: rRisk > 0 ? netPnl / rRisk : 0,
    status: 'closed',
    setup,
    playbook_id: playbookId,
    notes: pnlTarget > 0 ? 'Good execution, respected the plan.' : 'Should have cut sooner.',
    emotion_before: emotion,
    emotion_after: pnlTarget > 0 ? 'confident' : 'anxious',
    mistake_tags: pnlTarget < -100 ? ['early_exit'] : [],
    is_backtested: false,
    created_at: entryDate.toISOString(),
    updated_at: entryDate.toISOString(),
  }
}

export const MOCK_TRADES: Trade[] = [
  generateTrade(1, 'AAPL', 'long', 182.5, 100, 340, 'pb-1', 'VWAP', 'confident'),
  generateTrade(1, 'TSLA', 'short', 245.0, 50, -180, 'pb-2', 'ORB', 'anxious'),
  generateTrade(2, 'NVDA', 'long', 520.0, 30, 890, 'pb-1', 'Breakout', 'confident'),
  generateTrade(2, 'SPY', 'long', 450.0, 200, 420, 'pb-3', 'Pullback', 'calm'),
  generateTrade(3, 'AMZN', 'long', 178.0, 80, -240, 'pb-2', 'ORB', 'fearful'),
  generateTrade(3, 'META', 'long', 482.0, 40, 560, 'pb-1', 'VWAP', 'calm'),
  generateTrade(4, 'GOOGL', 'short', 165.0, 60, 320, 'pb-3', 'Pullback', 'confident'),
  generateTrade(5, 'MSFT', 'long', 415.0, 50, 780, 'pb-1', 'Breakout', 'confident'),
  generateTrade(5, 'QQQ', 'long', 385.0, 100, -160, 'pb-3', 'Pullback', 'calm'),
  generateTrade(6, 'AAPL', 'short', 185.0, 100, 270, 'pb-2', 'ORB', 'calm'),
  generateTrade(7, 'TSLA', 'long', 238.0, 60, 1200, 'pb-1', 'Breakout', 'confident'),
  generateTrade(8, 'AMD', 'long', 168.0, 75, -380, 'pb-2', 'ORB', 'anxious'),
  generateTrade(9, 'NVDA', 'short', 545.0, 25, 420, 'pb-1', 'VWAP', 'confident'),
  generateTrade(10, 'COIN', 'long', 185.0, 50, -220, 'pb-3', 'Pullback', 'fearful'),
  generateTrade(11, 'SPY', 'long', 448.0, 200, 640, 'pb-1', 'Breakout', 'calm'),
  generateTrade(12, 'AMZN', 'short', 182.0, 60, 180, 'pb-2', 'ORB', 'confident'),
  generateTrade(13, 'META', 'long', 478.0, 35, 490, 'pb-3', 'Pullback', 'calm'),
  generateTrade(14, 'MSFT', 'short', 418.0, 40, -130, 'pb-1', 'VWAP', 'anxious'),
  generateTrade(15, 'GOOGL', 'long', 163.0, 80, 560, 'pb-2', 'ORB', 'confident'),
  generateTrade(16, 'TSLA', 'long', 242.0, 55, 880, 'pb-1', 'Breakout', 'confident'),
  generateTrade(17, 'AMD', 'short', 172.0, 70, 340, 'pb-3', 'Pullback', 'calm'),
  generateTrade(18, 'AAPL', 'long', 180.0, 120, 720, 'pb-1', 'VWAP', 'confident'),
  generateTrade(19, 'QQQ', 'short', 388.0, 80, -280, 'pb-2', 'ORB', 'fearful'),
  generateTrade(20, 'NVDA', 'long', 510.0, 30, 1100, 'pb-1', 'Breakout', 'confident'),
  generateTrade(21, 'SPY', 'long', 445.0, 250, 375, 'pb-3', 'Pullback', 'calm'),
  generateTrade(22, 'META', 'short', 490.0, 30, 480, 'pb-1', 'VWAP', 'confident'),
  generateTrade(23, 'MSFT', 'long', 412.0, 55, 660, 'pb-2', 'ORB', 'calm'),
  generateTrade(24, 'AMZN', 'long', 175.0, 90, -420, 'pb-3', 'Pullback', 'anxious'),
  generateTrade(25, 'COIN', 'long', 180.0, 60, 540, 'pb-1', 'Breakout', 'confident'),
  generateTrade(26, 'TSLA', 'short', 250.0, 45, 360, 'pb-2', 'ORB', 'calm'),
  generateTrade(28, 'AAPL', 'long', 183.0, 100, 500, 'pb-1', 'VWAP', 'confident'),
  generateTrade(30, 'NVDA', 'long', 505.0, 35, -290, 'pb-3', 'Pullback', 'anxious'),
  generateTrade(32, 'GOOGL', 'long', 161.0, 85, 680, 'pb-1', 'Breakout', 'confident'),
  generateTrade(35, 'SPY', 'short', 452.0, 200, 800, 'pb-2', 'ORB', 'confident'),
  generateTrade(37, 'AMD', 'long', 165.0, 80, -180, 'pb-3', 'Pullback', 'fearful'),
  generateTrade(40, 'META', 'long', 472.0, 40, 920, 'pb-1', 'VWAP', 'confident'),
  generateTrade(42, 'MSFT', 'long', 408.0, 60, 480, 'pb-2', 'ORB', 'calm'),
  generateTrade(45, 'TSLA', 'long', 235.0, 65, 1560, 'pb-1', 'Breakout', 'confident'),
  generateTrade(47, 'AAPL', 'short', 188.0, 90, 630, 'pb-3', 'Pullback', 'calm'),
  generateTrade(50, 'QQQ', 'long', 380.0, 120, 960, 'pb-1', 'VWAP', 'confident'),
  generateTrade(52, 'NVDA', 'short', 530.0, 28, 560, 'pb-2', 'ORB', 'calm'),
  generateTrade(55, 'AMZN', 'long', 170.0, 100, -340, 'pb-3', 'Pullback', 'anxious'),
  generateTrade(57, 'COIN', 'short', 190.0, 50, 400, 'pb-1', 'Breakout', 'confident'),
  generateTrade(60, 'SPY', 'long', 440.0, 300, 900, 'pb-2', 'ORB', 'calm'),
  generateTrade(62, 'GOOGL', 'long', 158.0, 90, 720, 'pb-1', 'VWAP', 'confident'),
  generateTrade(65, 'AMD', 'long', 160.0, 90, 540, 'pb-3', 'Pullback', 'calm'),
  generateTrade(67, 'META', 'short', 498.0, 28, 392, 'pb-1', 'Breakout', 'confident'),
  generateTrade(70, 'TSLA', 'long', 228.0, 70, -420, 'pb-2', 'ORB', 'fearful'),
  generateTrade(72, 'AAPL', 'long', 176.0, 130, 1040, 'pb-1', 'VWAP', 'confident'),
  generateTrade(75, 'MSFT', 'long', 402.0, 65, 780, 'pb-3', 'Pullback', 'calm'),
]

// Open trade
MOCK_TRADES.push({
  id: 'trade-open-1',
  user_id: 'user-1',
  account_id: 'acc-1',
  symbol: 'NVDA',
  asset_type: 'stocks',
  side: 'long',
  quantity: 20,
  entry_price: 875.0,
  exit_price: null,
  entry_date: subHours(now, 3).toISOString(),
  exit_date: null,
  stop_loss: 858.0,
  take_profit: 920.0,
  commission: 0.1,
  gross_pnl: null,
  net_pnl: null,
  r_multiple: null,
  status: 'open',
  setup: 'Breakout',
  playbook_id: 'pb-1',
  notes: 'Breaking out of consolidation zone',
  emotion_before: 'confident',
  emotion_after: null,
  mistake_tags: [],
  is_backtested: false,
  created_at: subHours(now, 3).toISOString(),
  updated_at: subHours(now, 3).toISOString(),
})

export const MOCK_PSYCHOLOGY: PsychologyEntry[] = Array.from({ length: 20 }, (_, i) => ({
  id: `psych-${i}`,
  user_id: 'user-1',
  date: format(subDays(now, i * 2), 'yyyy-MM-dd'),
  mood_score: Math.floor(Math.random() * 4) + 6,
  energy_score: Math.floor(Math.random() * 4) + 5,
  confidence_score: Math.floor(Math.random() * 4) + 6,
  pre_session_notes: 'Ready to trade. Market looks bullish today.',
  post_session_notes: 'Good day overall. Followed the plan.',
  lessons_learned: 'Patience pays off. Wait for the setup.',
  goals_met: Math.random() > 0.3,
  followed_rules: Math.random() > 0.2,
  created_at: subDays(now, i * 2).toISOString(),
}))
